// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/analytics"
    | `/api/${string}`
    | "/api/analytics"
    | "/api/analytics/article-read"
    | "/api/analytics/export"
    | "/api/analytics/feed-interaction"
    | "/api/analytics/streaks"
    | "/api/articles"
    | `/api/articles/${string}`
    | `/api/articles/${string}/state`
    | "/api/articles/batch-update"
    | "/api/articles/mark-all-read"
    | "/api/auth/forgot-password"
    | "/api/auth/login"
    | "/api/auth/logout"
    | "/api/auth/refresh"
    | "/api/auth/register"
    | "/api/auth/reset-password"
    | `/api/auth/verify-email/${string}`
    | "/api/discovery/categories"
    | "/api/discovery/discover"
    | "/api/discovery/export/opml"
    | "/api/discovery/import/opml"
    | `/api/discovery/related/${string}`
    | "/api/discovery/search"
    | "/api/discovery/validate"
    | "/api/feeds"
    | `/api/feeds/${string}`
    | `/api/feeds/${string}/mark-all-read`
    | `/api/feeds/${string}/refresh`
    | "/api/feeds/page"
    | "/api/folders"
    | `/api/folders/${string}`
    | "/api/folders/reorder"
    | `/api/greader/${string}`
    | "/api/ping"
    | "/api/stats/history"
    | "/api/stats/overview"
    | "/api/stats/reading-time"
    | "/api/users/me"
    | "/api/users/me/avatar"
    | "/api/users/me/password"
    | "/api/users/me/settings"
    | "/discover"
    | "/folders"
    | "/health"
    | "/login"
    | "/ready"
    | "/register"
    | "/reset-password"
    | "/saved"
    | "/search"
    | "/settings"
    | "/statistics"
    | `/uploads/${string}`
    | "/verify-email"
  }
}

export {};
