// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/api/ping"
    | "/health"
    | "/ready"
  }
}

export {};
